on:
  workflow_dispatch:

jobs:
  deploy:
    name: "deploy to staging"
    runs-on: ubuntu-latest
    steps:
      - name: Create SSH Config on temporary VM
        run: |
          mkdir -p ~/.ssh/
          echo "$GCP_SSH_KEY" > ~/.ssh/gcp_ssh_key
          chmod 600 ~/.ssh/gcp_ssh_key
          cat ~/.ssh/gcp_ssh_key
          cat >>~/.ssh/config <<END
          Host gcp_vm
            HostName $GCP_SSH_IP
            User $GCP_SSH_USER
            IdentityFile ~/.ssh/gcp_ssh_key
            StrictHostKeyChecking no
          END
        env:
          GCP_SSH_USER: ${{ secrets.GCP_SSH_USER }}
          GCP_SSH_KEY: ${{ secrets.GCP_SSH_KEY }}
          GCP_SSH_IP: ${{ secrets.GCP_SSH_IP }}
          
      - name: SSH into the server
        run: |
          ssh gcp_vm 'ls -l'
