on:
  workflow_dispatch:

jobs:
  deploy:
    name: "deploy to staging"
    runs-on: ubuntu-latest
    steps:
      - name: Create priv key file on temporary VM
        run: |
          mkdir -p ~/.ssh/
          echo "${{ secrets.GCP_SSH_KEY }}" > ~/.ssh/gcp_ssh_key
          chmod 600 ~/.ssh/gcp_ssh_key
          cat ~/.ssh/gcp_ssh_key
          
      - name: SSH into the server
        run: |
          ssh -i ~/.ssh/gcp_ssh_key ${{ secrets.GCP_SSH_USER }}@${{ secrets.GCP_SSH_IP }} 'ls -l'
