on:
  workflow_dispatch:

jobs:
  my_job:
    name: deploy to staging
    runs-on: ubuntu-18.04

    steps:
    - uses: 'actions/checkout@v2'

    - id: 'auth'
      uses: 'google-github-actions/auth@v0'
      with:
        credentials_json: '${{ secrets.VM_SERVICEACC_1 }}'

    - id: 'echo'
      name: Run a one-line script
      run: echo Hello, world!
